
# name: Deploy  #action 的名称

# on: # event监听事件
#   push: #当代码push的时候
#     branches:
#       - main
#   workflow_dispatch:  #当手动触发的时候

# permissions:
#   contents: write # toekn的权限

# jobs:
#   deploy:
#     runs-on: ubuntu-latest  #基于ubuntu的镜像
#     steps:
#       - uses: actions/checkout@v2 #已经被封装好的行为  检出自定义分支
#       # - uses: actions/setup-node@v3
#       #   with:
#       #     node-version: 16
#       #     cache: yarn
#       # - run: yarn install

#       - name: Setup pnpm #行为名称
#         uses: pnpm/action-setup@v2  #安装依赖
#         with:
#           # 选择要使用的 pnpm 版本
#           version: 7
#           # 使用 pnpm 安装依赖
#           run_install: true

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           # 选择要使用的 node 版本
#           node-version: 18
#           # 缓存 pnpm 依赖
#           cache: pnpm

#       # 运行构建脚本
#       - name: Build VuePress site  #行为名称
#         run: pnpm build #编译代码

#       # - name: Build
#       #   run: yarn docs:build

#       - name: Deploy  #行为名称
#         uses: peaceiris/actions-gh-pages@v3  #使用已经封装好的action库
#         with:
#           deploy_key: ${{ secrets.ACTION_SECRET }}
#           publish_dir: dist
#           # build_dir: docs/.vuepress/dist
#           FOLDER: dist
#           CLEAN: true
#           publish_branch: gh-pages
#         env:
#           github_token: ${{ secrets.ACTION_SECRET }}
